SELECT * FROM USER_TABLES;
 -- use kimdb;
 -- show tables;

CREATE TABLE MEMBER(
	MID VARCHAR(20) PRIMARY KEY,
	MPW VARCHAR(20) NOT NULL,
	MNAME VARCHAR(20) NOT NULL,
	ROLE VARCHAR(20) NOT NULL
);

INSERT INTO MEMBER VALUES('admin','1234','관리자','ADMIN');

SELECT * FROM MEMBER;
